### ISSUE TITLE
Dead keys don't work

### ISSUE THREAD

**Issue by milouse** [cliqz-oss/browser-f#668] opened 2017-08-22 19:19 UTC
As I'm a french user, my linux box is configured with the fr_FR.utf8 locale, lang, etc. My main keyboard layout, defined in Mate desktop and x11 level is fr-bepo (a french dvorak variant). I'm using the deb version of cliqz (the bug exists for all cliqz version since 1.12 at least). I've a custom `.XCompose` file in my home folder, along with the following lines in my `.profile` file:

```
# Be sure we use the right .XCompose
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=none
```

## Step to reproduce

- click on any editable field on a page or in the interface
- enter `^` (dead_circumflex) followed by `u`

## Expected result

**û** should be printed.

## Actual result

**u** is printed.

Hitting several times `^` do not print anything, even if hitting it twice should produce a single ^.

I can observe the same behavior with all my dead keys (the one we frequently use in french at least) like `¨` and all my specific `.XCompose` key combinations.

cliqz is the only one application on my computer having this problem. I've no idea why :(

**Comment by milouse** [comment] 2017-08-22 19:23
I've tried again after having disabled my .XCompose and commented the corresponding .profile lines and it changes nothing.

**Comment by milouse** [comment] 2018-06-05 10:00
The problem is still there :/

**Comment by alver-cliqz** [comment] 2018-06-05 12:10
Sorry @milouse . Do you know how we can fix this? And is it exist for original FF?

**Comment by alver-cliqz** [comment] 2018-06-05 12:12
@luciancor, @chrmod could it be because of extension do not properly process keystroke?

**Comment by milouse** [comment] 2018-06-05 14:41
No, it does not exist on firefox. The bug is present in both the version compiled by you (fetched as deb or tar.bz2) and the one I build for archlinux.

However I never try to compile firefox myself. I suspect a problem with linked lib (libevent, xorg ?) but I cannot see major difference between regular firefox and cliqz build recipes.

The problem does not appear in cliqz for firefox.

**Comment by remusao** [comment] 2018-06-05 15:45
Hey @milouse,

I was not able to reproduce so far using the basic `azerty` layout on an Ubuntu 16.04 box. Could you maybe give this layout a shot and see if the issue persists?

**Comment by milouse** [comment] 2018-06-06 08:40
I try with an azerty layout too, same problem. It must really be a problem with an archlinux lib. Thus non blocking bug for you as you support only debian/ubuntu, but strange enough to let me look further on this. If I found something I let you know.

**Comment by luciancor** [comment] 2018-06-06 08:58
thanks for your input @milouse! Closing this issue for now but please let us  know if you find out more details ;)

**Closed by luciancor** 2018-06-06 08:58 UTC

**Comment by milouse** [comment] 2018-07-17 11:50
Very strange, with the last build, the bug always occurs on one of my computer, but not on the other one, freshly installed. I'm pretty sure both have the same configuration. I'll look further to find the diff between the two computers.

**Comment by milouse** [comment] 2018-07-17 11:55
Wow. I just deleted my cache and profile files from the old PC to simulate a cliqz fresh install… and the bug is gone. This should be related to some old profile preferences… but anyway I've now a fully working cliqz browser. I'm happy :)

**Comment by remusao** [comment] 2018-07-17 12:11
@milouse That is very nice to hear! I'm glad this mystery is now solved! Thanks a lot for spending the time to investigate.
