### ISSUE TITLE
Add custom string to User-Agent?

### ISSUE THREAD

**Issue by alver-cliqz** [cliqz-oss/browser-f#15] opened 2015-10-12 15:03 UTC
Now our product have the same UA, as original:
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0

Is it good idea to add our string into it? So any third-party company will be able to calculate our auditory. For example:
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0 CliqzFF/39.0

(suggest - better to add some text to "Cliqz", because in future we can have a lot of different Cliqz product)

**Comment by chrmod** [comment] 2015-10-22 14:08
duplicate of: https://github.com/cliqz-oss/browser-f/issues/28

**Closed by chrmod** 2015-10-22 14:08 UTC
Labels: duplicate
